[workspace]
resolver = "2"
members = [
    "aoc/day1",
    "aoc/day2", 
    "aoc/day3", 
    "aoc/day4", 
]

[workspace.dependencies]
clap = { version = "4.4.11" }
regex = { version = "1.10.2" }
lazy_static = { version = "1.4.0" }
utils = { path = "./aoc/pkg/utils"}
